### ISSUE TITLE
uasset files not showing/loading and crashing UE5.3 

### ISSUE THREAD

**Issue by MrJRules** [eddiebeazer/ue5-linter#6]
First, I wanted to say that you are appreciated for getting the plugin to compile for UE5.3. 

I would appreciate your help getting my current error using the 5.3 version downloaded from the tags page. I created a new project, added a Plugins folder and a Linter folder and I put all content from your zip in this folder. I then right clicked on the uproject file and selected Generate Visual Studio Project files, then opened and built the project. The plugin loads but there is an error with the assets outlined below.

I am getting the following error: The summary for the package '/Linter/MarketplaceLinter/MarketPlaceLintRuleset' is invalid.
In the below image you can see that the files are in the content director (lower right), but do not show up in the editor content browser. When I run Linter I get an editor crash. 
![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/e2a97074-2048-4aac-95d2-60b1c6bb5877)

Then, if I try to import the file I get an error saying:
![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/93d973a2-069f-491c-b5da-cb097e32a25f)

If this helps, I get an error for every asset I try to import into the content window like the above, and also in the load errors log window in editor as follows:
![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/501793a1-d9b4-419c-ab9b-53bab605816a)

Here is the crash report I receive from Unreal Crash window:
![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/c22697e4-8edd-4b5e-935c-0564170bc0a6)

Any reason this would happen? Is this on my end?

**Comment by eddiebeazer** [comment]
Hey, good news is that I still have this working fully in 5.3 for a few projects so I think it just may be with the way you have it extracted. 

I'm away from my computer this weekend so I will most likely won't be of much help until Monday. 

It looks like you did everything correctly. What I'll try to do is make a zip for the releases that can be extracted directly into the plugins directory

**Comment by MrJRules** [comment]
Good to hear. Thank you for this! I look forward to hearing from you Monday.

Can you explain what you mean by "the way you have it extracted". I am confused by this. I extracted it through winrar, through winzip, and through windows explorer, in multiple ways. First through drag and drop, second through extract here function, and so on. 

Thanks again for the help.

**Comment by MrJRules** [comment]
> Hey, good news is that I still have this working fully in 5.3 for a few projects so I think it just may be with the way you have it extracted.
> 
> I'm away from my computer this weekend so I will most likely won't be of much help until Monday.
> 
> It looks like you did everything correctly. What I'll try to do is make a zip for the releases that can be extracted directly into the plugins directory

Good to hear. Thank you for this! I look forward to hearing from you Monday.

Can you explain what you mean by "the way you have it extracted". I am confused by this. I extracted it through winrar, through winzip, and through windows explorer, in multiple ways. First through drag and drop, second through extract here function, and so on. 

Thanks again for the help.

**Comment by MrJRules** [comment]
> Can you try to delete the Linter folder under your plugins folder and then follow the directions in the readme. I just updated them

Same issue is happening. 

![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/2ae4d554-6a56-4e00-92a3-cec4583f9aff)

uassets are there in explorer but are not valid when in unreal. 

When I open the MarketplaceLintRuleSet.uasset in Notepad++, this is what I see.

![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/a08978da-dd3d-41f9-91d0-db169d0fb0d2)

Any other thoughts? Could these assets be redirects on your project, pointing the the correct files somewhere else?

**Comment by MrJRules** [comment]
I even tried to build in MS Visual Studio 2022. 

![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/27cd6be5-593a-497e-ba1a-60e422571412)

**Comment by MrJRules** [comment]
Even the icon does not show up in the content browser but show in explorer.

![image](https://github.com/eddiebeazer/ue5-linter/assets/88682304/c19bf7f9-6490-4020-893a-7182664325a0)

**Comment by MrJRules** [comment]
Yeah, I created a blank c++ project. Here is the link to the project zip. I do hope this yields good news. Our team would really do well to have a tool to help with consistency.

[Linter_5_3.zip](https://drive.google.com/file/d/1zDTqFLMoEeVhlVwY_pEhuS_QzHWrButs/view?usp=sharing)

Thank you for your help!

**Comment by eddiebeazer** [comment]
I got it working.  I don't know if one of the files in the repo got corrupted, but when I diffed it in LFS it looked correct still.  I just copied my content directory from my personal project into what you sent me and it worked fine.  When I do the 5.4 update I'll try to see if I can clean that up a bit so this doesn't happen again. 

Delete your content directory in PLugins/Linter/Content and replace it with these.  That should work 

[Content.zip](https://github.com/eddiebeazer/ue5-linter/files/12718649/Content.zip)

**Comment by MrJRules** [comment]
That worked! Thank you!!!
 I am not sure what is different because it all looks the same. Can you explain what happened?

**Comment by eddiebeazer** [comment]
Honestly I don't know.  I wonder if someone else will run into this same issue.  Something seemed corrupted in your plugins content folder.  I know my games version of the linter was working fine so I just copied my content folder to the project you shared with me(All the changes I've made to the Linter plugin was just the source files).

What makes it strange to me is that Git LFS didn't notice a difference in the files.  Unless someone else has this issue I'm going to assume it just might have been a fluke, glad to see it working!

**Comment by MrJRules** [comment]
Okay, I appreciate your time and help with this. Thank you!

**Comment by eddiebeazer** [comment]
No problem, I'm going to close this for now. Let me know if you need anything else

**Comment by matt-edmondson** [comment]
I think I have the answer to this, and a workaround.

The repo has the correct files, but the releases don't.

My guess is the way you're making your release builds doesn't have LFS support installed, so the zip files you're producing have LFS pointers in that directory rather than the actual uasset files.

The workaround for users trying to install the plugin is to clone the repo directly with a client that has LFS support installed instead of downloading the zip.

The proposed fix in #9 I'm assuming would have the same issue if the next release was built with the same release pipeline.

**Comment by eddiebeazer** [comment]
> I think I have the answer to this, and a workaround.
> 
> The repo has the correct files, but the releases don't.
> 
> My guess is the way you're making your release builds doesn't have LFS support installed, so the zip files you're producing have LFS pointers in that directory rather than the actual uasset files.
> 
> The workaround for users trying to install the plugin is to clone the repo directly with a client that has LFS support installed instead of downloading the zip.
> 
> The proposed fix in #9 I'm assuming would have the same issue if the next release was built with the same release pipeline.

I rarely use LFS so I forgot that could have been the issue.  When its time for 5.4 I think I'll just create the releases via actions and hopefully that should solve it for everyone who has been downloading the autogenerated releases.  I also think I manually uploaded a zip that you should just be able to unzip directly in your plugins folder
