### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by xuelongmu** [eddiebeazer/ue5-linter#8]
Hi,

Thank you for upgrading this plugin from the original version by Allar. I was wondering if you are able to specify a license for this repo, for example, an MIT license. It will help me use it in more projects. The original repo from Allar is MIT licensed for what it's worth: https://github.com/ue4plugins/Linter/

Thank you!

**Comment by eddiebeazer** [comment]
Added a MIT in master.  Thanks for that, only reason I didn't have a license there was due to me not being able to find that repo
